# arb-dir: lib/l10n
# template-arb-file: intl_ar.arb
# output-localization-file: app_localizations.dart


arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-class: S
output-localization-file: s.dart
